### ISSUE TITLE
Indicate current version in documentation

### ISSUE THREAD

**Issue by animeshchat** [haroldadmin/opengraphKt#2]
Firstly, thank you for the super useful library!

Currently I could not find an easy way to get the current version number to put in the build file and resorted to brute force in order to find the version number to be used is:

    implementation "com.github.haroldadmin:opengraphKt:0.0.2"

Maybe indicate the current version somewhere in the docs?

Thanks again!

**Comment by haroldadmin** [comment]
Hi! Thank you for using this library!


The latest version of the library is indicated by the small Jitpack icon just below the `implementation ...` line.

As of right now, it's `0.0.3`.

An alternative way to find release notes and versions is to use the [Releases tab](https://github.com/haroldadmin/opengraphKt/releases) on the repository.

**Comment by haroldadmin** [comment]
@animeshchat I'm closing this issue now. Please open another one if you need more help.
